[package]
name = "predicate-logic-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id_tree = "1.8.0"
id_tree_layout = "2.0.4"
